# Generated by Django 5.2.1 on 2025-05-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ruthapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseactivity",
            name="type_id",
        ),
        migrations.RemoveField(
            model_name="courseactivity",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="studentactivitylog",
            name="activity_id",
        ),
        migrations.RemoveField(
            model_name="studentactivitylog",
            name="stu_id",
        ),
        migrations.DeleteModel(
            name="ActivityType",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseActivity",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="StudentActivityLog",
        ),
    ]
