# Generated by Django 5.2.1 on 2025-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("age", models.IntegerField()),
                ("course_id", models.IntegerField()),
                ("quiz_count", models.IntegerField()),
                ("quiz_avg_duration", models.IntegerField()),
                ("individual_assignment_count", models.IntegerField()),
                ("individual_assignment_avg_duration", models.IntegerField()),
                ("group_assignment_count", models.IntegerField()),
                ("group_assignment_avg_duration", models.IntegerField()),
                ("forum_count", models.IntegerField()),
                ("forum_avg_duration", models.IntegerField()),
                ("predicted_difficulty", models.CharField(max_length=10)),
                ("recommendation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "jenyapp_prediction",
            },
        ),
    ]
