# Generated by Django 5.2.1 on 2025-05-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DropoutPredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("total_activities_done", models.IntegerField()),
                ("total_duration_minutes", models.FloatField()),
                ("prediction", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
