# Generated by Django 5.2.1 on 2025-05-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mellyapp", "0002_anomalydetectionlog_clusteranomalylog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropoutExistLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("total_activities_done", models.IntegerField()),
                ("total_duration_minutes", models.FloatField()),
                ("prediction", models.CharField(max_length=10)),
                ("probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "stu_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enroll_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_id", models.CharField(max_length=20)),
                ("grade", models.FloatField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mellyapp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.CharField(max_length=50)),
                ("activity_start", models.DateTimeField()),
                ("activity_end", models.DateTimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mellyapp.student",
                    ),
                ),
            ],
        ),
    ]
