# Generated by Django 5.2 on 2025-05-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_count', models.IntegerField()),
                ('login_days', models.IntegerField()),
                ('total_study_time', models.IntegerField()),
                ('avg_time_per_activity', models.IntegerField()),
                ('avg_active_hour', models.IntegerField()),
                ('grade_mean', models.IntegerField()),
                ('grade_stddev', models.IntegerField()),
                ('dominant_activity_type', models.CharField(max_length=30)),
                ('algorithm', models.CharField(max_length=10)),
                ('predicted_segment', models.CharField(max_length=50)),
            ],
        ),
    ]
