# Generated by Django 5.2 on 2025-05-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valenciaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_count', models.IntegerField()),
                ('login_days', models.IntegerField()),
                ('total_study_time', models.IntegerField()),
                ('avg_time_per_activity', models.IntegerField()),
                ('avg_active_hour', models.IntegerField()),
                ('grade_mean', models.IntegerField()),
                ('grade_stddev', models.IntegerField()),
                ('dominant_activity_type_forum', models.BooleanField(default=False)),
                ('dominant_activity_type_group_assignment', models.BooleanField(default=False)),
                ('dominant_activity_type_individual_assignment', models.BooleanField(default=False)),
                ('algorithm', models.CharField(choices=[('xgboost', 'XGBoost'), ('kmeans', 'K-Means')], max_length=20)),
                ('predicted_segment', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionLog',
        ),
    ]
